// HaulBoX Load Document Locking, Versioning & RBAC Permissions Engine
// Enforces lifecycle document locking, multi-version audit history, and Super Admin overrides.

const kv = require('./kvstore');

/**
 * Checks if a specific document type is locked based on the load's lifecycle state.
 * Lifecycle stages:
 * - 'ASSIGNED' / 'NOT_STARTED': RC editable, BOL/POD pending
 * - 'START_TRIP' / 'GOING_TO_PICKUP' / 'ARRIVED_PICKUP': RC is LOCKED, BOL editable
 * - 'LOADED' / 'GOING_TO_DELIVERY' / 'ARRIVED_DELIVERY': RC is LOCKED, BOL is LOCKED, POD editable
 * - 'COMPLETED' / 'LOCKED': RC, BOL, POD, and Photos are ALL LOCKED
 */
function isDocumentLocked(docType, loadStatus = 'ASSIGNED') {
  const status = String(loadStatus).toUpperCase();
  const type = String(docType).toUpperCase();

  // If the load is completed, EVERYTHING is locked
  if (status === 'COMPLETED' || status === 'LOCKED' || status === 'ARCHIVED') {
    return true;
  }

  // RC locks as soon as trip starts (GOING_TO_PICKUP onwards)
  if (type === 'RC' || type === 'RATE_CONFIRMATION') {
    return status !== 'ASSIGNED' && status !== 'NOT_STARTED' && status !== 'PENDING';
  }

  // BOL locks once loaded / going to delivery
  if (type === 'BOL' || type === 'BILL_OF_LADING' || type === 'BOL_PICTURES') {
    return status === 'GOING_TO_DELIVERY' || status === 'ARRIVED_DELIVERY' || status === 'DELIVERED';
  }

  // POD locks once accepted / completed
  if (type === 'POD' || type === 'PROOF_OF_DELIVERY' || type === 'POD_PICTURES') {
    return status === 'POD_ACCEPTED' || status === 'COMPLETED';
  }

  return false;
}

/**
 * Evaluates whether a user role can upload/replace a specific document on a load
 */
function canUserModifyDocument({ userRole = 'driver', docType, loadStatus = 'ASSIGNED' }) {
  const role = String(userRole).toLowerCase().replace(/\s+/g, '');

  // Super Admin can ALWAYS modify / override, even if locked
  if (role === 'superadmin' || role === 'super_admin') {
    return { allowed: true, isOverride: isDocumentLocked(docType, loadStatus) };
  }

  const locked = isDocumentLocked(docType, loadStatus);
  if (locked) {
    return {
      allowed: false,
      reason: `Document "${docType}" is locked in load state "${loadStatus}". Only Super Admin can modify locked load documents.`,
    };
  }

  // Authorized roles can edit unlocked documents
  if (['driver', 'dispatcher', 'admin'].includes(role)) {
    return { allowed: true, isOverride: false };
  }

  return { allowed: false, reason: 'Unauthorized role' };
}

/**
 * Retrieves all documents and version history for a load with lock metadata
 */
async function getLoadDocuments(loadId, userRole = 'driver') {
  const key = `load_docs:${loadId}`;
  const raw = await kv.get(key).catch(() => null);
  let docs = raw ? JSON.parse(raw) : null;

  if (!docs) {
    // Default initial documents structure for load
    docs = {
      loadId,
      status: 'ASSIGNED',
      documents: {
        RC: {
          title: 'Rate Confirmation (RC)',
          docType: 'RC',
          status: 'VERIFIED',
          currentVersion: 1,
          versions: [
            {
              version: 1,
              filename: 'RC_HB1042_TQL.pdf',
              uploadedBy: 'HaulBoX Dispatcher (Sarah M.)',
              uploadedAt: new Date().toISOString(),
              size: '1.2 MB',
              notes: 'Initial Rate Confirmation generated by dispatch.',
            },
          ],
        },
        BOL: {
          title: 'Bill of Lading (BOL)',
          docType: 'BOL',
          status: 'NOT_UPLOADED',
          currentVersion: 0,
          versions: [],
        },
        BOL_PICTURES: {
          title: 'BOL Supporting Pictures',
          docType: 'BOL_PICTURES',
          status: 'NOT_UPLOADED',
          currentVersion: 0,
          versions: [],
        },
        POD: {
          title: 'Proof of Delivery (POD)',
          docType: 'POD',
          status: 'NOT_UPLOADED',
          currentVersion: 0,
          versions: [],
        },
        POD_PICTURES: {
          title: 'POD Supporting Pictures',
          docType: 'POD_PICTURES',
          status: 'NOT_UPLOADED',
          currentVersion: 0,
          versions: [],
        },
      },
    };
    await kv.set(key, JSON.stringify(docs));
  }

  // Attach dynamic permissions & lock flags based on requester role and load state
  const loadStatus = docs.status || 'ASSIGNED';
  const result = {};

  for (const [type, doc] of Object.entries(docs.documents)) {
    const locked = isDocumentLocked(type, loadStatus);
    const perm = canUserModifyDocument({ userRole, docType: type, loadStatus });

    result[type] = {
      ...doc,
      isLocked: locked,
      canView: true, // All authorized users can ALWAYS view
      canReplace: perm.allowed,
      isSuperAdminOverride: perm.isOverride,
    };
  }

  return {
    loadId,
    loadStatus,
    documents: result,
  };
}

/**
 * Replaces or uploads a new document version with full audit history
 */
async function replaceLoadDocument({
  loadId,
  docType,
  filename,
  fileUrl,
  uploadedBy,
  userRole = 'driver',
  reason = '',
  aiVerificationResult = null,
}) {
  const key = `load_docs:${loadId}`;
  const raw = await kv.get(key).catch(() => null);
  const data = raw ? JSON.parse(raw) : (await getLoadDocuments(loadId, userRole));

  const loadStatus = data.status || 'ASSIGNED';
  const perm = canUserModifyDocument({ userRole, docType, loadStatus });

  if (!perm.allowed) {
    throw new Error(perm.reason || 'Permission denied: Document is locked.');
  }

  const type = docType.toUpperCase();
  if (!data.documents[type]) {
    data.documents[type] = {
      title: type,
      docType: type,
      status: 'NOT_UPLOADED',
      currentVersion: 0,
      versions: [],
    };
  }

  const doc = data.documents[type];
  const newVersionNum = (doc.currentVersion || 0) + 1;

  const versionRecord = {
    version: newVersionNum,
    filename: filename || `${type}_v${newVersionNum}.jpg`,
    fileUrl: fileUrl || `https://storage.haulbox.internal/loads/${loadId}/${type}/v${newVersionNum}`,
    uploadedBy: uploadedBy || userRole,
    userRole,
    uploadedAt: new Date().toISOString(),
    isSuperAdminOverride: perm.isOverride,
    reason: reason || (perm.isOverride ? 'Super Admin manual correction' : 'Driver/Dispatcher document update'),
    aiVerification: aiVerificationResult,
  };

  // Archive previous versions & set new active version
  doc.versions.push(versionRecord);
  doc.currentVersion = newVersionNum;
  doc.status = aiVerificationResult?.overallStatus || 'UPLOADED';

  await kv.set(key, JSON.stringify(data));

  // Also log into global audit trail
  const auditKey = `audit_doc_changes`;
  const auditRaw = await kv.get(auditKey).catch(() => null);
  const auditList = auditRaw ? JSON.parse(auditRaw) : [];
  auditList.unshift({
    loadId,
    docType: type,
    version: newVersionNum,
    uploadedBy,
    userRole,
    timestamp: new Date().toISOString(),
    reason: versionRecord.reason,
  });
  await kv.set(auditKey, JSON.stringify(auditList.slice(0, 100)));

  return {
    ok: true,
    document: doc,
    version: versionRecord,
  };
}

module.exports = {
  isDocumentLocked,
  canUserModifyDocument,
  getLoadDocuments,
  replaceLoadDocument,
};
